### ISSUE TITLE
A question about esphome custom components

### ISSUE THREAD

**Issue by jeremiahsb** [sonocotta/esparagus-media-center#23]
With the esphome releases in 2025, the team has removed custom components:
https://esphome.io/guides/contributing#a-note-about-custom-components

Are there any plans to migrate the esphome yaml to use external components?
https://esphome.io/components/external_components

**Comment by anabolyc** [comment]
Hey @jeremiahsb 
Absolutely, yes. It is a work in progress and tracked in the sister repo [here](https://github.com/sonocotta/esp32-audio-dock/issues/35). The working branch is [here](https://github.com/sonocotta/esp32-tas5805m-dac/pull/1)

I'm trying to add DSP capabilities at the same time, like EQ so it takes a bit more time than I'd hope for.

**Comment by anabolyc** [comment]
While work is still in progress, I'm posting the config that works for me (external component work is not finalized yet). It is based on esp-idf and compared to the Arduino implementation, it works much better, no glitches and much more stable, at least based on my limited experience. bonus points, this implements a 15-band equalizer, with -15..+15dB regulation, works really amazing, really looking forward to having it finalized

```yaml

substitutions:
  name: esphome-web-dc73f8
  friendly_name: louder-esp32
  task_stack_in_psram: "false"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.11.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
  # on_boot:
  #   priority: 600  # After most components are initialized
  #   then:
  #     - lambda: |-
  #         id(tas5805m_dac).set_volume(int(id(current_volume)));
  #         ESP_LOGI("tas5805m", "Restored volume on boot: %.0f", id(current_volume));
esp32:
  board: mhetesp32minikit
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.1.5

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  platform: esphome
  password: !secret esphome_ota_password

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  ap:
    ssid: "$name Hotspot"
    password: !secret esphome_ap_password

captive_portal:

psram:
  speed: 80MHz

#  - source: /config/esphome/esp32-tas5805m-dac/esphome/components
#  - source: /config/esphome/external/esphome-components-test/components
external_components:
  - source: github://mrtoy-me/esphome-components-test@dev
    components: [ tas5805m ]
    refresh: 0s

# script:
#   - id: set_volume
#     parameters:
#       level: float
#     then:
#       - lambda: |-
#           id(current_volume) = level;
#           id(tas5805m_dac).set_volume(int(level));
#           ESP_LOGI("tas5805m", "Volume set to: %.0f", level);

globals:
  - id: current_volume
    type: float
  - id: eq_gain_refreshed
    type: bool
    initial_value: "false"

i2c:
  sda: GPIO21
  scl: GPIO27
  frequency: 400kHz
  scan: True

audio_dac:
  - platform: tas5805m
    id: tas5805m_dac
    enable_pin: GPIO33
    analog_gain: -9db

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO26

speaker:
  - platform: i2s_audio
    id: speaker_id
    dac_type: external
    i2s_dout_pin: GPIO22
    audio_dac: tas5805m_dac
    channel: stereo
    sample_rate: 48000
    timeout: never

  - platform: mixer
    id: mixer_speaker_id
    task_stack_in_psram: ${task_stack_in_psram}
    output_speaker: speaker_id
    source_speakers:
      - id: announcement_spk_mixer_input
        timeout: never
      - id: media_spk_mixer_input
        timeout: never

  - platform: resampler
    id: media_spk_resampling_input
    task_stack_in_psram: ${task_stack_in_psram}
    output_speaker: media_spk_mixer_input

  - platform: resampler
    id: announcement_spk_resampling_input
    task_stack_in_psram: ${task_stack_in_psram}
    output_speaker: announcement_spk_mixer_input

media_player:
  - platform: speaker
    name: Louder Mediaplayer
    id: louder_mediaplayer
    task_stack_in_psram: ${task_stack_in_psram}
    volume_increment: 0.5%
    volume_min: 45%
    volume_max: 80%
    media_pipeline:
      speaker: media_spk_resampling_input
      num_channels: 2
    announcement_pipeline:
      speaker: announcement_spk_resampling_input
      num_channels: 1

    on_play:
      - if:
          condition:
            switch.is_off: enable_louder
          then:
            switch.turn_on: enable_louder
      - wait_until:
                media_player.is_playing:
      - delay: 0.5s
      - if:
          condition:
            and:
              - switch.is_on: enable_eq_control
              - lambda: return (!id(eq_gain_refreshed));
          then:
            - lambda: |-
                ESP_LOGI("tas5805m", "Refreshing EQ gains (on play)");            
                id(tas5805m_dac).refresh_eq_gains();
                id(eq_gain_refreshed) = true;

    on_announcement:
      - if:
          condition:
            switch.is_off: enable_louder
          then:
            switch.turn_on: enable_louder

      - lambda: id(current_volume) = id(tas5805m_dac).volume();

      - mixer_speaker.apply_ducking:
            id: media_spk_mixer_input
            decibel_reduction: 40
            duration: 0.25s
      - wait_until:
            media_player.is_announcing:
      - delay: 0.75s
      - if:
          condition:
            and:
              - switch.is_on: enable_eq_control
              - lambda: return (!id(eq_gain_refreshed));
          then:
            - lambda: |-
                ESP_LOGD("tas5805m", "Refreshing EQ gains (on announcement)");            
                id(tas5805m_dac).refresh_eq_gains();
                id(eq_gain_refreshed) = true;

      - lambda: id(tas5805m_dac).set_volume(id(announce_volume).state / 100);
      - wait_until:
          not:
            media_player.is_announcing:
      - mixer_speaker.apply_ducking:
            id: media_spk_mixer_input
            decibel_reduction: 0
            duration: 2.0s
      - lambda: id(tas5805m_dac).set_volume(id(current_volume));

number:
  - platform: template
    name: Announce Volume
    id: announce_volume
    icon: mdi:volume-source
    unit_of_measurement: "%"
    min_value: 0
    max_value: 100
    step: 1
    initial_value: 50
    restore_value: true
    optimistic: true

  # - platform: template
  #   name: "DAC Volume"
  #   id: dac_volume
  #   min_value: 0
  #   max_value: 100
  #   step: 1
  #   initial_value: 50
  #   restore_value: true
  #   optimistic: true
  #   on_value:
  #     then:
  #       - script.execute:
  #           id: set_volume
  #           level: !lambda "return x;"

  - platform: template
    name: Gain ---20 Hz
    id: eq_band_0_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda:
        id(tas5805m_dac).set_eq_gain(0, id(eq_band_0_gain).state);

  - platform: template
    name: Gain ---31.5 Hz
    id: eq_band_1_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda:
        id(tas5805m_dac).set_eq_gain(1, id(eq_band_1_gain).state);

  - platform: template
    name: Gain ---50 Hz
    id: eq_band_2_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(2, id(eq_band_2_gain).state);

  - platform: template
    name: Gain ---80 Hz
    id: eq_band_3_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(3, id(eq_band_3_gain).state);

  - platform: template
    name: Gain --125 Hz
    id: eq_band_4_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(4, id(eq_band_4_gain).state);

  - platform: template
    name: Gain --200 Hz
    id: eq_band_5_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(5, id(eq_band_5_gain).state);

  - platform: template
    name: Gain --315 Hz
    id: eq_band_6_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(6, id(eq_band_6_gain).state);

  - platform: template
    name: Gain --500 Hz
    id: eq_band_7_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(7, id(eq_band_7_gain).state);

  - platform: template
    name: Gain --800 Hz
    id: eq_band_8_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(8, id(eq_band_8_gain).state);

  - platform: template
    name: Gain -1250 Hz
    id: eq_band_9_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(9, id(eq_band_9_gain).state);

  - platform: template
    name: Gain -2000 Hz
    id: eq_band_10_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(10, id(eq_band_10_gain).state);

  - platform: template
    name: Gain -3150 Hz
    id: eq_band_11_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(11, id(eq_band_11_gain).state);

  - platform: template
    name: Gain -5000 Hz
    id: eq_band_12_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(12, id(eq_band_12_gain).state);

  - platform: template
    name: Gain -8000 Hz
    id: eq_band_13_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(13, id(eq_band_13_gain).state);

  - platform: template
    name: Gain 16000 Hz
    id: eq_band_14_gain
    icon: mdi:volume-source
    unit_of_measurement: "dB"
    min_value: -15
    max_value: 15
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true
    on_value:
      lambda: id(tas5805m_dac).set_eq_gain(14, id(eq_band_14_gain).state);

switch:
  - platform: template
    name: Enable
    id: enable_louder
    optimistic: true
    restore_mode: ALWAYS_ON
    turn_on_action:
      lambda: id(tas5805m_dac).set_deep_sleep_off();
    turn_off_action:
      lambda: id(tas5805m_dac).set_deep_sleep_on();

  - platform: template
    name: Enable EQ Control
    id: enable_eq_control
    optimistic: true
    restore_mode: ALWAYS_ON
    turn_on_action:
      - lambda: id(tas5805m_dac).set_eq_on();
      - if:
          condition:
            and:
              - media_player.is_playing:
              - lambda: return (!id(eq_gain_refreshed));
          then:
            - lambda: |-
                id(tas5805m_dac).refresh_eq_gains();
                id(eq_gain_refreshed) = true;

    turn_off_action:
      - lambda: id(tas5805m_dac).set_eq_off();

interval:
  - interval: 30s
    then:
      - if:
          condition:
            - switch.is_on: enable_louder
            - for:
                time: 120s
                condition:
                  or:
                    - media_player.is_idle: louder_mediaplayer
                    - media_player.is_paused: louder_mediaplayer
          then:
            - switch.turn_off: enable_louder
```
